# You are editing:
# PRODUCTION
namespace: production

# Router Service (router.geist.im)
router:
  name: geist-router
  replicas: 2
  image:
    repository: alo42/router
    pullPolicy: Always
    tag: production-latest
  service:
    name: geist-router
    port: 8000
  env:
    NODE_ENV: production
    PORT: 8000
    API_URL: https://router.geist.im
    INFERENCE_URL: https://inference.geist.im
    EMBEDDINGS_URL: https://embeddings.geist.im

  # Speech-to-Text (Whisper) configuration
  whisper:
    enabled: true
    modelPath: /models/ggml-base.bin
    binaryPath: /usr/local/bin/whisper-cli

  # Optional volume mounts (used when whisper.enabled=true)
  volumeMounts:
    - name: stt-models
      mountPath: /models
      readOnly: true

  # Volumes for the pod (hostPath, same pattern as LLM)
  volumes:
    - name: stt-models
      hostPath:
        path: /root/whisper-models

# Inference Service (inference.geist.im)
inference:
  name: geist-inference
  replicas: 2
  image:
    repository: alo42/inference
    pullPolicy: Always
    tag: production-latest
  service:
    name: geist-inference
    port: 8001
  env:
    NODE_ENV: production
    PORT: 8001
    API_URL: https://router.geist.im
    INFERENCE_URL: https://inference.geist.im
    EMBEDDINGS_URL: https://embeddings.geist.im

# Embeddings Service (embeddings.geist.im)
embeddings:
  name: geist-embeddings
  replicas: 2
  image:
    repository: alo42/embeddings
    pullPolicy: Always
    tag: production-latest
  service:
    name: geist-embeddings
    port: 8002
  env:
    NODE_ENV: production
    PORT: 8002
    API_URL: https://router.geist.im
    INFERENCE_URL: https://inference.geist.im
    EMBEDDINGS_URL: https://embeddings.geist.im

# Webapp Service (webapp.geist.im)
webapp:
  name: geist-webapp
  replicas: 2
  image:
    repository: alo42/webapp
    pullPolicy: Always
    tag: production-latest
  service:
    name: geist-webapp
    port: 3000
  env:
    NODE_ENV: production
    PORT: 3000
    API_URL: https://router.geist.im
    INFERENCE_URL: https://inference.geist.im
    EMBEDDINGS_URL: https://embeddings.geist.im

# Ingress Configuration
ingress:
  ingressClassName: nginx
  name: geist-production
  router:
    name: geist-router-ingress
    host: router.geist.im
  inference:
    name: geist-inference-ingress
    host: inference.geist.im
  embeddings:
    name: geist-embeddings-ingress
    host: embeddings.geist.im
  webapp:
    name: geist-webapp-ingress
    host: webapp.geist.im
