# You are editing:
# DEVELOPMENT
namespace: development
# Router Service (api.geist.im)
router:
  name: geist-router
  replicas: 1
  image:
    repository: alo42/router
    pullPolicy: Always
    tag: development-1.1.2
  service:
    name: geist-router
    port: 8000
  env:
    NODE_ENV: development
    PORT: 8000
    API_URL: https://api.geist.im
    INFERENCE_URL: https://inference.geist.im
    EMBEDDINGS_URL: https://embeddings.geist.im
  # Whisper STT service URL (external service)
  whisperServiceUrl: http://whisper-stt-service:8000
# Inference Service (inference.geist.im)
inference:
  name: geist-inference
  replicas: 1
  image:
    repository: alo42/inference
    pullPolicy: Always
    tag: development-1.0.14
  service:
    name: geist-inference
    port: 8080
  env:
    NODE_ENV: development
    PORT: 8080
    API_URL: https://api.geist.im
    INFERENCE_URL: https://inference.geist.im
    EMBEDDINGS_URL: https://embeddings.geist.im
# Whisper STT Service (whisper-stt.geist.im)
whisper:
  name: geist-whisper-stt
  replicas: 1
  image:
    repository: alo42/whisper-stt
    pullPolicy: Always
    tag: development-1.0.3
  service:
    name: whisper-stt-service
    port: 8000
  env:
    NODE_ENV: development
    PORT: 8000
    WHISPER_BINARY_PATH: /usr/local/bin/whisper-cli
    WHISPER_MODEL_PATH: /models/ggml-base.bin
  models:
    hostPath: /root/whisper-models
  ingress:
    name: whisper-stt-ingress
    host: whisper-stt.geist.im
    secretName: whisper-stt-tls
# Embeddings Service (embeddings.geist.im)
embeddings:
  name: geist-embeddings
  replicas: 1
  image:
    repository: alo42/embeddings
    pullPolicy: Always
    tag: development-1.0.8
  service:
    name: geist-embeddings
    port: 8001
  env:
    NODE_ENV: development
    PORT: 8001
    API_URL: https://api.geist.im
    INFERENCE_URL: https://inference.geist.im
    EMBEDDINGS_URL: https://embeddings.geist.im
# Webapp Service (webapp.geist.im)
webapp:
  name: geist-webapp
  replicas: 1
  image:
    repository: alo42/webapp
    pullPolicy: Always
    tag: development-1.0.6
  service:
    name: geist-webapp
    port: 3000
  env:
    NODE_ENV: development
    PORT: 3000
    API_URL: https://api.geist.im
    INFERENCE_URL: https://inference.geist.im
    EMBEDDINGS_URL: https://embeddings.geist.im
# Ingress Configuration
ingress:
  ingressClassName: nginx
  name: geist-development
  router:
    name: geist-router-ingress
    host: api.geist.im
  inference:
    name: geist-inference-ingress
    host: inference.geist.im
  embeddings:
    name: geist-embeddings-ingress
    host: embeddings.geist.im
  webapp:
    name: geist-webapp-ingress
    host: webapp.geist.im
whisper-stt:
  image:
    tag: development-1.0.4
