# You are editing:
# DEVELOPMENT
namespace: development

# Router Service (router.geist.im)
router:
  name: geist-router
  replicas: 1
  image:
    repository: alo42/router
    pullPolicy: Always
    tag: development-1.0.13
  service:
    name: geist-router
    port: 8000
  env:
    NODE_ENV: development
    PORT: 8000
    API_URL: https://router.geist.im
    INFERENCE_URL: https://inference.geist.im
    EMBEDDINGS_URL: https://embeddings.geist.im

# Inference Service (inference.geist.im)
inference:
  name: geist-inference
  replicas: 1
  image:
    repository: alo42/inference
    pullPolicy: Always
    tag: latest
  service:
    name: geist-inference
    port: 8001
  env:
    NODE_ENV: development
    PORT: 8001
    API_URL: https://router.geist.im
    INFERENCE_URL: https://inference.geist.im
    EMBEDDINGS_URL: https://embeddings.geist.im

# Embeddings Service (embeddings.geist.im)
embeddings:
  name: geist-embeddings
  replicas: 1
  image:
    repository: alo42/embeddings
    pullPolicy: Always
    tag: latest
  service:
    name: geist-embeddings
    port: 8002
  env:
    NODE_ENV: development
    PORT: 8002
    API_URL: https://router.geist.im
    INFERENCE_URL: https://inference.geist.im
    EMBEDDINGS_URL: https://embeddings.geist.im

# Webapp Service (webapp.geist.im)
webapp:
  name: geist-webapp
  replicas: 1
  image:
    repository: alo42/webapp
    pullPolicy: Always
    tag: latest
  service:
    name: geist-webapp
    port: 3000
  env:
    NODE_ENV: development
    PORT: 3000
    API_URL: https://router.geist.im
    INFERENCE_URL: https://inference.geist.im
    EMBEDDINGS_URL: https://embeddings.geist.im

# Ingress Configuration
ingress:
  ingressClassName: nginx
  name: geist-development
  router:
    name: geist-router-ingress
    host: router.geist.im
  inference:
    name: geist-inference-ingress
    host: inference.geist.im
  embeddings:
    name: geist-embeddings-ingress
    host: embeddings.geist.im
  webapp:
    name: geist-webapp-ingress
    host: webapp.geist.im
