apiVersion: v1
kind: Service
metadata:
  name: {{.Values.api.service.name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.api.name}}
spec:
  clusterIP: None
  selector:
    app: {{.Values.api.name}}
  ports:
    - port: {{.Values.api.service.port}}
      name: http
